"""
OptiQuant IA — CSV to Premium Excel Dashboard Generator (MVP)

Usage:
    pip install pandas xlsxwriter
    python csv_to_excel_dashboard.py input.csv output_dashboard.xlsx

What it does:
    1. Loads a CSV
    2. Detects dates, numeric metrics and categorical dimensions
    3. Builds a dashboard_spec deterministically
    4. Generates a premium Excel workbook:
       - Dashboard
       - Data
       - Insights
       - Data Quality
       - About

No LLM required for this MVP.
"""

from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd


@dataclass
class DatasetProfile:
    row_count: int
    column_count: int
    date_columns: list[str]
    numeric_columns: list[str]
    categorical_columns: list[str]
    missing_by_column: dict[str, int]
    duplicate_rows: int
    quality_score: int


def normalize_col(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(name).strip().lower()).strip("_")


def load_csv(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    try:
        df = pd.read_csv(path, sep=None, engine="python")
    except Exception:
        df = pd.read_csv(path, encoding="latin1", sep=None, engine="python")

    df.columns = [str(c).strip() for c in df.columns]
    return df


def profile_dataset(df: pd.DataFrame) -> DatasetProfile:
    date_columns, numeric_columns, categorical_columns = [], [], []

    for col in df.columns:
        s = df[col]

        if pd.api.types.is_numeric_dtype(s):
            numeric_columns.append(col)
            continue

        parsed = pd.to_datetime(s, errors="coerce", dayfirst=False)
        if parsed.notna().mean() >= 0.70:
            date_columns.append(col)
            continue

        coerced_num = pd.to_numeric(
            s.astype(str).str.replace(",", ".", regex=False).str.replace(r"[^\d\.\-]", "", regex=True),
            errors="coerce",
        )
        if coerced_num.notna().mean() >= 0.70:
            df[col] = coerced_num
            numeric_columns.append(col)
        else:
            categorical_columns.append(col)

    missing_by_column = df.isna().sum().to_dict()
    duplicate_rows = int(df.duplicated().sum())

    total_cells = max(df.shape[0] * df.shape[1], 1)
    missing_cells = int(df.isna().sum().sum())
    quality_score = max(0, min(100, round(100 - (missing_cells / total_cells) * 60 - (duplicate_rows / max(len(df), 1)) * 40)))

    return DatasetProfile(
        row_count=len(df),
        column_count=len(df.columns),
        date_columns=date_columns,
        numeric_columns=numeric_columns,
        categorical_columns=categorical_columns,
        missing_by_column=missing_by_column,
        duplicate_rows=duplicate_rows,
        quality_score=quality_score,
    )


def pick_column(columns: list[str], keywords: list[str]) -> str | None:
    normalized = {c: normalize_col(c) for c in columns}
    for col, norm in normalized.items():
        if any(k in norm for k in keywords):
            return col
    return None


def build_dashboard_spec(df: pd.DataFrame, profile: DatasetProfile) -> dict[str, Any]:
    amount_col = pick_column(profile.numeric_columns, ["revenue", "sales", "amount", "total", "price", "turnover", "ca"]) or (
        profile.numeric_columns[0] if profile.numeric_columns else None
    )
    date_col = pick_column(profile.date_columns, ["date", "month", "day", "created", "order"]) or (
        profile.date_columns[0] if profile.date_columns else None
    )
    product_col = pick_column(profile.categorical_columns, ["product", "item", "sku", "category", "service"]) or (
        profile.categorical_columns[0] if profile.categorical_columns else None
    )
    region_col = pick_column(profile.categorical_columns, ["region", "country", "city", "location", "market"])
    customer_col = pick_column(profile.categorical_columns, ["customer", "client", "company", "account"])
    status_col = pick_column(profile.categorical_columns, ["status", "state", "stage"])

    dashboard_type = "sales_performance" if amount_col else "generic_executive"

    title = "Sales Performance Dashboard" if dashboard_type == "sales_performance" else "Executive Data Dashboard"

    return {
        "dashboard_type": dashboard_type,
        "title": title,
        "subtitle": "Generated by OptiQuant IA from your CSV export",
        "metric_column": amount_col,
        "date_column": date_col,
        "primary_dimension": product_col,
        "region_column": region_col,
        "customer_column": customer_col,
        "status_column": status_col,
        "quality_score": profile.quality_score,
        "row_count": profile.row_count,
        "column_count": profile.column_count,
    }


def safe_sum(series: pd.Series) -> float:
    return float(pd.to_numeric(series, errors="coerce").fillna(0).sum())


def safe_mean(series: pd.Series) -> float:
    s = pd.to_numeric(series, errors="coerce").dropna()
    return float(s.mean()) if len(s) else 0.0


def aggregate_for_charts(df: pd.DataFrame, spec: dict[str, Any]) -> dict[str, pd.DataFrame]:
    metric = spec.get("metric_column")
    date_col = spec.get("date_column")
    dim = spec.get("primary_dimension")
    region = spec.get("region_column")
    status = spec.get("status_column")

    result: dict[str, pd.DataFrame] = {}

    if metric and date_col:
        tmp = df[[date_col, metric]].copy()
        tmp[date_col] = pd.to_datetime(tmp[date_col], errors="coerce")
        tmp = tmp.dropna(subset=[date_col])
        if not tmp.empty:
            tmp["Period"] = tmp[date_col].dt.to_period("M").astype(str)
            result["trend"] = tmp.groupby("Period", as_index=False)[metric].sum().tail(12)

    if metric and dim:
        result["top_dimension"] = (
            df.groupby(dim, dropna=False)[metric]
            .sum()
            .sort_values(ascending=False)
            .head(10)
            .reset_index()
        )

    if metric and region:
        result["region"] = (
            df.groupby(region, dropna=False)[metric]
            .sum()
            .sort_values(ascending=False)
            .head(8)
            .reset_index()
        )

    if status:
        result["status"] = df[status].fillna("Unknown").value_counts().head(8).reset_index()
        result["status"].columns = [status, "Count"]

    return result


def write_table(ws, start_row: int, start_col: int, df: pd.DataFrame, workbook, header_fmt, cell_fmt, max_rows: int | None = None):
    if max_rows is not None:
        df = df.head(max_rows)
    for c, col in enumerate(df.columns):
        ws.write(start_row, start_col + c, col, header_fmt)
    for r, (_, row) in enumerate(df.iterrows(), start=1):
        for c, value in enumerate(row):
            ws.write(start_row + r, start_col + c, value, cell_fmt)
    return start_row + len(df) + 1


def generate_excel_dashboard(csv_path: str | Path, output_path: str | Path) -> dict[str, Any]:
    df = load_csv(csv_path)
    profile = profile_dataset(df)
    spec = build_dashboard_spec(df, profile)
    charts_data = aggregate_for_charts(df, spec)

    output_path = Path(output_path)

    with pd.ExcelWriter(output_path, engine="xlsxwriter") as writer:
        workbook = writer.book

        # Theme
        bg = "#F7F9FC"
        navy = "#0F1B2D"
        text = "#132033"
        muted = "#667085"
        teal = "#00B894"
        teal_dark = "#008C72"
        border = "#E5EAF2"
        card = "#FFFFFF"
        purple = "#7C3AED"
        blue = "#2563EB"
        orange = "#F59E0B"

        title_fmt = workbook.add_format({"bold": True, "font_size": 24, "font_color": navy, "bg_color": bg})
        subtitle_fmt = workbook.add_format({"font_size": 11, "font_color": muted, "bg_color": bg})
        section_fmt = workbook.add_format({"bold": True, "font_size": 13, "font_color": navy, "bg_color": card, "border": 1, "border_color": border})
        card_title_fmt = workbook.add_format({"font_size": 9, "font_color": muted, "bg_color": card})
        card_value_fmt = workbook.add_format({"bold": True, "font_size": 20, "font_color": navy, "bg_color": card})
        card_delta_fmt = workbook.add_format({"font_size": 9, "font_color": teal_dark, "bg_color": card})
        card_box_fmt = workbook.add_format({"bg_color": card, "border": 1, "border_color": border, "valign": "vcenter"})
        header_fmt = workbook.add_format({"bold": True, "font_color": navy, "bg_color": "#EEFDF8", "border": 1, "border_color": border})
        cell_fmt = workbook.add_format({"font_color": text, "bg_color": card, "border": 1, "border_color": border})
        money_fmt = workbook.add_format({"font_color": text, "bg_color": card, "border": 1, "border_color": border, "num_format": "#,##0 €"})
        pct_fmt = workbook.add_format({"font_color": text, "bg_color": card, "border": 1, "border_color": border, "num_format": "0.0%"})
        small_fmt = workbook.add_format({"font_color": muted, "font_size": 9, "bg_color": bg})
        accent_fmt = workbook.add_format({"bold": True, "font_color": teal_dark, "bg_color": bg})

        # Sheets
        dashboard = workbook.add_worksheet("Dashboard")
        data_sheet = workbook.add_worksheet("Data")
        insights = workbook.add_worksheet("Insights")
        quality = workbook.add_worksheet("Data Quality")
        about = workbook.add_worksheet("About")

        for ws in [dashboard, data_sheet, insights, quality, about]:
            ws.hide_gridlines(2)

        # Data sheet
        df.to_excel(writer, sheet_name="Data", index=False)
        data_sheet = writer.sheets["Data"]
        data_sheet.freeze_panes(1, 0)
        data_sheet.set_tab_color(teal)
        for i, col in enumerate(df.columns):
            data_sheet.set_column(i, i, min(max(len(str(col)) + 2, 12), 28))

        # Dashboard layout
        dashboard.set_tab_color(teal)
        dashboard.set_zoom(90)
        dashboard.set_column("A:A", 3)
        dashboard.set_column("B:G", 14)
        dashboard.set_column("H:M", 14)
        dashboard.set_column("N:S", 14)
        dashboard.set_column("T:T", 3)
        for r in range(1, 46):
            dashboard.set_row(r - 1, 22)
        dashboard.conditional_format("A1:T46", {"type": "no_errors", "format": workbook.add_format({"bg_color": bg})})

        dashboard.merge_range("B2:M2", spec["title"], title_fmt)
        dashboard.merge_range("B3:M3", spec["subtitle"], subtitle_fmt)
        dashboard.write_rich_string("B4", accent_fmt, "OptiQuant IA", subtitle_fmt, "  · CSV to Excel Dashboard Generator")
        dashboard.merge_range("P2:S3", "Excel-ready workbook", workbook.add_format({
            "bold": True, "font_color": "#FFFFFF", "bg_color": teal_dark, "align": "center", "valign": "vcenter", "border": 1, "border_color": teal_dark
        }))

        metric = spec.get("metric_column")
        total = safe_sum(df[metric]) if metric else len(df)
        avg = safe_mean(df[metric]) if metric else 0
        dim = spec.get("primary_dimension")
        top_dim = str(df[dim].mode().iloc[0]) if dim and not df[dim].dropna().empty else "N/A"

        kpis = [
            ("Total Value", total, "Generated from detected metric", money_fmt if metric else cell_fmt),
            ("Rows", profile.row_count, "Total records analyzed", cell_fmt),
            ("Average Value", avg, "Mean of selected metric", money_fmt if metric else cell_fmt),
            ("Quality Score", profile.quality_score / 100, "Data readiness score", pct_fmt),
            ("Top Segment", top_dim, "Most frequent category", cell_fmt),
        ]

        # KPI cards
        card_ranges = ["B6:D9", "E6:G9", "H6:J9", "K6:M9", "N6:S9"]
        card_starts = [(5,1), (5,4), (5,7), (5,10), (5,13)]
        for (title, value, desc, fmt), rng, (row, col) in zip(kpis, card_ranges, card_starts):
            dashboard.merge_range(rng, "", card_box_fmt)
            dashboard.write(row, col, title, card_title_fmt)
            if title == "Quality Score":
                dashboard.write(row + 1, col, value, card_value_fmt)
                dashboard.write(row + 1, col + 1, "", pct_fmt)
            else:
                dashboard.write(row + 1, col, value, card_value_fmt)
            dashboard.write(row + 2, col, desc, card_delta_fmt)

        # Write chart data hidden-ish on far right
        helper_col = 22
        helper_row = 1
        chart_positions = []

        if "trend" in charts_data:
            trend = charts_data["trend"]
            end = write_table(dashboard, helper_row, helper_col, trend, workbook, header_fmt, cell_fmt)
            chart = workbook.add_chart({"type": "line"})
            chart.set_title({"name": "Trend Over Time", "name_font": {"color": navy, "bold": True}})
            chart.add_series({
                "name": spec.get("metric_column") or "Metric",
                "categories": ["Dashboard", helper_row + 1, helper_col, end - 1, helper_col],
                "values": ["Dashboard", helper_row + 1, helper_col + 1, end - 1, helper_col + 1],
                "line": {"color": teal, "width": 2.5},
                "marker": {"type": "circle", "size": 5, "border": {"color": teal}, "fill": {"color": teal}},
            })
            chart.set_chartarea({"fill": {"color": card}, "border": {"color": border}})
            chart.set_plotarea({"fill": {"color": card}, "border": {"color": border}})
            chart.set_legend({"none": True})
            chart.set_x_axis({"num_font": {"color": muted}})
            chart.set_y_axis({"major_gridlines": {"visible": True, "line": {"color": border}}, "num_font": {"color": muted}})
            dashboard.insert_chart("B12", chart, {"x_scale": 1.55, "y_scale": 1.18})
            helper_row = end + 2

        if "top_dimension" in charts_data:
            top = charts_data["top_dimension"]
            end = write_table(dashboard, helper_row, helper_col, top, workbook, header_fmt, cell_fmt)
            chart = workbook.add_chart({"type": "bar"})
            chart.set_title({"name": f"Top {spec.get('primary_dimension') or 'Segments'}", "name_font": {"color": navy, "bold": True}})
            chart.add_series({
                "categories": ["Dashboard", helper_row + 1, helper_col, end - 1, helper_col],
                "values": ["Dashboard", helper_row + 1, helper_col + 1, end - 1, helper_col + 1],
                "fill": {"color": teal},
                "border": {"none": True},
            })
            chart.set_chartarea({"fill": {"color": card}, "border": {"color": border}})
            chart.set_plotarea({"fill": {"color": card}, "border": {"color": border}})
            chart.set_legend({"none": True})
            chart.set_x_axis({"major_gridlines": {"visible": True, "line": {"color": border}}, "num_font": {"color": muted}})
            chart.set_y_axis({"num_font": {"color": muted}})
            dashboard.insert_chart("K12", chart, {"x_scale": 1.35, "y_scale": 1.18})
            helper_row = end + 2

        if "region" in charts_data:
            region_df = charts_data["region"]
            end = write_table(dashboard, helper_row, helper_col, region_df, workbook, header_fmt, cell_fmt)
            chart = workbook.add_chart({"type": "doughnut"})
            chart.set_title({"name": "Distribution", "name_font": {"color": navy, "bold": True}})
            chart.add_series({
                "categories": ["Dashboard", helper_row + 1, helper_col, end - 1, helper_col],
                "values": ["Dashboard", helper_row + 1, helper_col + 1, end - 1, helper_col + 1],
                "points": [{"fill": {"color": c}} for c in [teal, blue, purple, orange, "#10B981", "#60A5FA", "#A78BFA", "#FBBF24"]],
            })
            chart.set_hole_size(55)
            chart.set_chartarea({"fill": {"color": card}, "border": {"color": border}})
            chart.set_legend({"position": "right", "font": {"color": muted}})
            dashboard.insert_chart("B27", chart, {"x_scale": 1.15, "y_scale": 1.0})
            helper_row = end + 2

        # Insights and recommendations
        dashboard.merge_range("K27:S37", "", card_box_fmt)
        dashboard.write("K27", "AI-style Business Understanding", section_fmt)
        detected_lines = [
            f"Detected dashboard type: {spec['dashboard_type']}",
            f"Metric column: {spec.get('metric_column') or 'Not detected'}",
            f"Date column: {spec.get('date_column') or 'Not detected'}",
            f"Primary dimension: {spec.get('primary_dimension') or 'Not detected'}",
            f"Rows analyzed: {profile.row_count}",
            f"Data quality score: {profile.quality_score}%",
        ]
        for i, line in enumerate(detected_lines, start=29):
            dashboard.write(f"K{i}", "✓ " + line, workbook.add_format({"font_color": text, "bg_color": card, "font_size": 10}))

        dashboard.merge_range("B39:S43", "", workbook.add_format({"bg_color": "#EEFDF8", "border": 1, "border_color": "#B7F4E6"}))
        dashboard.write("B39", "Next step with OptiQuant IA Operator", workbook.add_format({"bold": True, "font_size": 13, "font_color": navy, "bg_color": "#EEFDF8"}))
        dashboard.write("B41", "Connect this dashboard to Google Sheets, OneDrive or recurring CSV exports for automatic refresh and governed workflows.", workbook.add_format({"font_color": text, "bg_color": "#EEFDF8"}))

        # Hide helper columns
        dashboard.set_column(helper_col, helper_col + 6, None, None, {"hidden": True})

        # Insights sheet
        insights.write("A1", "Insights", title_fmt)
        insight_list = [
            "Dashboard generated deterministically from CSV structure.",
            "Use this workbook as a decision-ready starting point.",
            "Connect recurring sources to move from one-off reporting to operational intelligence.",
        ]
        for i, item in enumerate(insight_list, start=3):
            insights.write(f"A{i}", "• " + item, subtitle_fmt)
        insights.set_column("A:A", 120)

        # Data quality sheet
        quality.write("A1", "Data Quality Report", title_fmt)
        qdf = pd.DataFrame({
            "Column": list(profile.missing_by_column.keys()),
            "Missing Values": list(profile.missing_by_column.values()),
        })
        qdf.to_excel(writer, sheet_name="Data Quality", startrow=3, index=False)
        quality.write("A3", "Column", header_fmt)
        quality.write("B3", "Missing Values", header_fmt)
        quality.write("D4", "Duplicate rows", header_fmt)
        quality.write("E4", profile.duplicate_rows, cell_fmt)
        quality.write("D5", "Quality score", header_fmt)
        quality.write("E5", profile.quality_score / 100, pct_fmt)
        quality.set_column("A:A", 28)
        quality.set_column("B:E", 18)

        # About sheet
        about.write("A1", "About this workbook", title_fmt)
        about.write("A3", "Generated by OptiQuant IA — CSV to Excel Dashboard Generator", subtitle_fmt)
        about.write("A5", "This file is an MVP-generated dashboard. It contains no macros and can be edited directly in Excel.", subtitle_fmt)
        about.write("A7", "CTA: Connect your spreadsheet source with OptiQuant IA for automatic refresh.", accent_fmt)
        about.set_column("A:A", 120)

    return {"output": str(output_path), "spec": spec, "profile": profile.__dict__}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("csv_path", help="Input CSV file path")
    parser.add_argument("output_path", nargs="?", default="optiquant_dashboard.xlsx", help="Output XLSX path")
    args = parser.parse_args()

    result = generate_excel_dashboard(args.csv_path, args.output_path)
    print(f"Generated: {result['output']}")
    print(f"Dashboard type: {result['spec']['dashboard_type']}")
    print(f"Rows: {result['profile']['row_count']} | Columns: {result['profile']['column_count']}")
    print(f"Quality score: {result['profile']['quality_score']}%")


if __name__ == "__main__":
    main()
