from __future__ import annotations

import json
import logging
from typing import Any, TypedDict

from app.core.config import Settings
from .fallback import build_deterministic_ai_report
from .schemas import AIContext, AIReport

logger = logging.getLogger(__name__)


class AIAnalystState(TypedDict, total=False):
    ai_context: dict[str, Any]
    ai_report: dict[str, Any] | None
    errors: list[str]
    used_fallback: bool


RAW_ROW_KEYWORDS = {"raw_rows", "rows", "sample_rows", "row_samples", "records", "dataframe", "raw_df", "clean_df"}

SYSTEM_PROMPT = """You are an AI Dashboard Analyst.

You do not receive raw CSV rows.
You only receive a compact JSON report generated by a Python data profiling and cleaning engine.

Your job:
- Write an executive-ready analysis.
- Explain the state of the data before and after cleaning.
- Highlight business-relevant insights.
- Suggest practical next actions.
- Avoid overclaiming.
- Do not invent facts not supported by the JSON.
- Keep the tone professional, clear, concise and persuasive.
- The output will be inserted into an Excel dashboard.

Rules:
- Return only the requested structured JSON.
- Do not mention unavailable information.
- Do not pretend to know the business context beyond the provided JSON.
- Keep executive_summary under 900 characters.
- Keep each insight/action/risk under 240 characters.
"""


def run_ai_analyst_graph(ai_context: dict[str, Any], *, settings: Settings) -> dict[str, Any]:
    try:
        from langgraph.graph import END, START, StateGraph
    except Exception as exc:  # noqa: BLE001 - optional dependency fallback during local tests.
        logger.warning("LangGraph unavailable, using fallback AI report: %s", exc)
        return {
            "ai_report": build_deterministic_ai_report(ai_context),
            "metadata": _metadata(settings, used_fallback=True, errors=[str(exc)]),
        }

    def validate_context_node(state: AIAnalystState) -> AIAnalystState:
        errors = list(state.get("errors", []))
        try:
            AIContext.model_validate(state["ai_context"])
            serialized = json.dumps(state["ai_context"], ensure_ascii=True, separators=(",", ":"))
            if len(serialized) > settings.max_ai_context_chars:
                errors.append("AI context exceeds configured max size")
            if _contains_raw_row_keys(state["ai_context"]):
                errors.append("AI context contains forbidden raw-row-like keys")
        except Exception as exc:  # noqa: BLE001
            errors.append(f"Invalid AI context: {exc}")
        return {**state, "errors": errors}

    def generate_ai_report_node(state: AIAnalystState) -> AIAnalystState:
        errors = list(state.get("errors", []))
        try:
            report = _call_llm_structured(state["ai_context"], settings=settings)
            return {**state, "ai_report": report, "errors": errors}
        except Exception as exc:  # noqa: BLE001
            logger.warning("LLM AI analyst generation failed safely: %s", exc)
            errors.append(f"LLM generation failed: {exc}")
            return {**state, "errors": errors}

    def validate_ai_report_node(state: AIAnalystState) -> AIAnalystState:
        errors = list(state.get("errors", []))
        try:
            report = AIReport.model_validate(state.get("ai_report")).model_dump()
            report["executive_summary"] = report["executive_summary"][:900]
            report["key_insights"] = [item[:240] for item in report["key_insights"][:5]]
            report["recommended_actions"] = [item[:240] for item in report["recommended_actions"][:5]]
            report["risk_notes"] = [item[:240] for item in report["risk_notes"][:5]]
            return {**state, "ai_report": AIReport.model_validate(report).model_dump(), "errors": errors}
        except Exception as exc:  # noqa: BLE001
            errors.append(f"Invalid AI report: {exc}")
            return {**state, "ai_report": None, "errors": errors}

    def fallback_node(state: AIAnalystState) -> AIAnalystState:
        return {
            **state,
            "ai_report": build_deterministic_ai_report(state["ai_context"]),
            "used_fallback": True,
        }

    def route_after_context(state: AIAnalystState) -> str:
        return "fallback_node" if state.get("errors") else "generate_ai_report_node"

    def route_after_generation(state: AIAnalystState) -> str:
        return "fallback_node" if state.get("errors") or not state.get("ai_report") else "validate_ai_report_node"

    def route_after_validation(state: AIAnalystState) -> str:
        return "fallback_node" if state.get("errors") or not state.get("ai_report") else END

    graph = StateGraph(AIAnalystState)
    graph.add_node("validate_context_node", validate_context_node)
    graph.add_node("generate_ai_report_node", generate_ai_report_node)
    graph.add_node("validate_ai_report_node", validate_ai_report_node)
    graph.add_node("fallback_node", fallback_node)
    graph.add_edge(START, "validate_context_node")
    graph.add_conditional_edges("validate_context_node", route_after_context)
    graph.add_conditional_edges("generate_ai_report_node", route_after_generation)
    graph.add_conditional_edges("validate_ai_report_node", route_after_validation)
    graph.add_edge("fallback_node", END)
    compiled = graph.compile()
    final_state = compiled.invoke({"ai_context": ai_context, "ai_report": None, "errors": [], "used_fallback": False})
    return {
        "ai_report": AIReport.model_validate(final_state["ai_report"]).model_dump(),
        "metadata": _metadata(settings, used_fallback=bool(final_state.get("used_fallback")), errors=final_state.get("errors", [])),
    }


def _call_llm_structured(ai_context: dict[str, Any], *, settings: Settings) -> dict[str, Any]:
    from langchain_core.messages import HumanMessage, SystemMessage
    from langchain_openai import ChatOpenAI

    llm = ChatOpenAI(
        model=settings.ai_analyst_model,
        temperature=0.2,
        timeout=settings.ai_analyst_timeout_seconds,
        api_key=settings.openai_api_key,
    )
    structured = llm.with_structured_output(AIReport)
    result = structured.invoke([
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(
            content=(
                "Analyze the following compact dataset report and generate the AI dashboard report:\n\n"
                + json.dumps(ai_context, ensure_ascii=True, separators=(",", ":"))
            )
        ),
    ])
    if isinstance(result, AIReport):
        return result.model_dump()
    return AIReport.model_validate(result).model_dump()


def _contains_raw_row_keys(value: Any) -> bool:
    if isinstance(value, dict):
        for key, item in value.items():
            normalized = str(key).lower()
            if normalized in RAW_ROW_KEYWORDS:
                return True
            if _contains_raw_row_keys(item):
                return True
    elif isinstance(value, list):
        return any(_contains_raw_row_keys(item) for item in value)
    return False


def _metadata(settings: Settings, *, used_fallback: bool, errors: list[str]) -> dict[str, Any]:
    return {
        "provider": "langgraph",
        "model": settings.ai_analyst_model if settings.openai_api_key else None,
        "used_fallback": used_fallback,
        "errors": [str(error)[:300] for error in errors[:3]],
    }
